<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
      <UserSecretsId>a8000826-1e21-4291-8fe0-69ea5a3566a7</UserSecretsId>
  </PropertyGroup>

</Project>
